# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Project_config = debug

else ifeq ($(config),release)
  Project_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Project

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Project:
ifneq (,$(Project_config))
	@echo "==== Building Project ($(Project_config)) ===="
	@${MAKE} --no-print-directory -C Project -f Makefile config=$(Project_config)
endif

clean:
	@${MAKE} --no-print-directory -C Project -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Project"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"